;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;background = ${xrdb:color0:#222}
background = #2E343E
background-alt = #2E343E
;foreground = ${xrdb:color7:#222}
foreground = #ffffff
foreground-alt = #ffffff
primary = #1b9fc6
secondary = #ffffff
alert = #bd2c40

[bar/memory]
;monitor = ${env:MONITOR:HDMI-1}
width = 3.25%
height = 24
offset-x = 84.1%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-center = memory

separator =

wm-restack = bspwm

[bar/tray]
;monitor = ${env:MONITOR:HDMI-1}
width = 0.1%
height = 24
offset-x = 83.75%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-center = blank

separator =

wm-restack = bspwm

tray-position = right
tray-detached = false
tray-maxsize = 23
tray-background = ${colors.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0


[bar/cpu]
;monitor = ${env:MONITOR:HDMI-1}
width = 3.25%
height = 24
offset-x = 87.65%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-center = cpu

separator =

wm-restack = bspwm

[bar/power]
width = 1.5%
height = 24
offset-x = 97.95%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-center = power

separator =

wm-restack = bspwm

[bar/audio]
width = 6.5%
height = 24
offset-x = 91.15%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-center = alsa

separator =

wm-restack = bspwm

[bar/ws]
width = 22%
height = 24
offset-x = 39%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #94bef2

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=10;3
font-1 = Iosevka Nerd Font:pixelsize=10;3

modules-center = xworkspaces

separator = " "

wm-restack = bspwm

[bar/arch]

width = 1.5%
height = 24
offset-x = 0.75%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 1
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

#font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-0 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=10;3
#font-0 = unifont:fontformat=truetype:size=10:antialias=false;2
#font-0 = siji:style=Regular:pixelsize=24;2
font-1 = Iosevka Nerd Font:pixelsize=10;3

modules-center = arch

separator = " "

wm-restack = bspwm

[bar/date]
width = 5.75%
height = 24
offset-x = 2.5%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=11;3

modules-center = date2

separator =

cursor-click = pointer
eursor-scroll = ns-resize

wm-restack = bspwm

[bar/time]
width = 4%
height = 24
offset-x = 8.6%
offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=11;3

modules-center = time

separator =

cursor-click = pointer
eursor-scroll = ns-resize

wm-restack = bspwm


[module/pacman-updates]
type = custom/script
exec = checkupdates | wc -l
interval = 1000
label = Updates: %output%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = " "
format-prefix-foreground = #ffbb00

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
format = <label>

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-underline = ${colors.secondary}

label-layout = %layout%
label-layout-underline = ${colors.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.secondary}
label-indicator-underline = ${colors.secondary}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted =  %free%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

; Separator in between workspaces
label-separator = "   "

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = 

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;♝
ws-icon-4 = 5;♞
ws-icon-default = 

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused =%icon%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-padding = 1

; visible = Active workspace on unfocused monitor
label-visible = %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1


; Separator in between workspaces
; label-separator = |


[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>

icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 

label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "﬙   "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #f90000
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "    "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #4bffdc
label = %percentage_used%%

[module/wlan]
type = internal/network
interface = net1
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = enp1s0
interval = 3.0

format-connected-underline = #55aa55
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 1

date = " %Y-%m-%d"

time = "%H:%M:%S "

format-prefix = "    "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%

[module/time]
type = internal/date
interval = 1

time = "%H:%M"

format-prefix = "  "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%


[module/date2]
type = internal/date
interval = 1

date = " %Y-%m-%d"

format-prefix = "   "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = #0a6cf5

label = %date% %time%


[module/pulseaudio]
type = internal/pulseaudio

click-right = exec pavucontrol &

format-volume = <label-volume>
label-volume =     %percentage%%
label-volume-foreground = ${root.foreground}

label-muted =     Shh!
label-muted-foreground = ${root.foreground}

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/alsa]
type = internal/alsa

click-right = exec pavucontrol &

format-volume = <label-volume> <bar-volume>
label-volume = "%percentage%%  "
label-volume-foreground = ${root.foreground}

format-muted-prefix = "     "
format-muted-foreground = ${colors.foreground-alt}
label-muted = shhh!

bar-volume-width = 10
bar-volume-foreground-0 = #55aa55
bar-volume-foreground-1 = #55aa55
bar-volume-foreground-2 = #55aa55
bar-volume-foreground-3 = #55aa55
bar-volume-foreground-4 = #55aa55
bar-volume-foreground-5 = #f5a70a
bar-volume-foreground-6 = #ff5555
bar-volume-gradient = false
bar-volume-indicator = |
bar-volume-indicator-font = 2
bar-volume-fill = ─
bar-volume-fill-font = 2
bar-volume-empty = ─
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.foreground-alt}

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-underline = #ffb52a

format-discharging = <animation-discharging> <label-discharging>
format-discharging-underline = ${self.format-charging-underline}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.foreground-alt}
format-full-underline = ${self.format-charging-underline}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-foreground = ${colors.foreground-alt}
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-foreground = ${colors.foreground-alt}
animation-discharging-framerate = 750

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
format-underline = #f50a4d
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/power]
type = custom/text

content = "   "
click-left = /home/tdm/.config/rofi/powermenu/powermenu.sh

[module/arch]
type = custom/text

content = "    "

click-left = /home/tdm/.config/rofi/launchers/misc/launcher.sh

[module/blank]
type = custom/text

content = " "

[module/line]
type = custom/text

content = "|"

[module/xworkspaces]
type = internal/xworkspaces

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Create click handler used to focus desktop
; Default: true
enable-click = true

; Create scroll handlers used to cycle desktops
; Default: true
enable-scroll = true

reverse-scroll = true


; icon-[0-9]+ = <desktop-name>;<icon>
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktops using:
; $ xprop -root _NET_DESKTOP_NAMES
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-6 = 7;ﭮ
icon-7 = 8;
icon-8 = 9;
icon-9 = 0;

icon-default =    

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
; Default: <label-state>
format = <label-state>
format-background = ${color.background-alt}
format-foreground = ${color.foreground}
format-overline = ${color.background}
format-underline = ${color.background}
format-padding = 1

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-active = %icon%
label-active-foreground = #a1d3ff

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-occupied = %icon%
label-occupied-foreground = #f2ffcc

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-urgent = %icon%
label-urgent-foreground = #ff7066

; Available tokens:
;   %name%
;   %icon%
;   %index%
; Default: %icon%  %name%
label-empty = %icon%
label-empty-foreground = 90e8f4ff

label-active-padding = 5
label-urgent-padding = 5
label-occupied-padding = 5
label-empty-padding = 5

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
;pseudo-transparency = false

[global/wm]
margin-top = 5
margin-bottom = 5

; vim:ft=dosini

[bar/i3]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 24
offset-y = 0%
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0
line-color = #00564d

border-size = 0
border-color = #0D00564d

padding-left = 0
padding-right = 1

module-margin-left = 1
module-margin-right = 1

font-0 = Droid Sans Mono:style=Regular:pixelsize=10;2
font-1 = Font Awesome 5 Brands Regular:style=Regular:pixelsize=12;2
font-2 = unifont:fontformat=truetype:size=14:antialias=false;2
font-3 = siji:style=Regular:pixelsize=24;2
font-4 = Iosevka Nerd Font:pixelsize=10;3

modules-left = blank arch line xworkspaces
modules-center = 
modules-right = pulseaudio blank memory blank cpu blank date2 blank time blank power blank

separator =

tray-position = right
tray-detached = false
tray-maxsize = 23
tray-background = ${colors.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0


